@note_id = 569cc9a6-9a9e-4c94-99c5-d9879f7d465c

### Create Note
POST http://localhost:8080/notes

{
    "title": "My First Note",
    "content": "This is the content of the first note.",
    "author": "John Doe"
}

### GET all
GET http://localhost:8080/notes

### GET Note by id
GET http://localhost:8080/notes/{{note_id}}

### Update Note by id
PUT http://localhost:8080/notes/{{note_id}}
Content-Type: application/json

{
  "title": "Updated Title 331141",
  "content": "Updated Content 12",
  "author": "New Author"
}

### Delete Note by id
DELETE http://localhost:8080/notes/{{note_id}}
