@note_id = 967640b2-0984-4d28-94b3-e410cd69f320

### Create Note
POST http://localhost:8080/notes


### GET all
GET http://localhost:8080/notes

### GET Note by id
GET http://localhost:8080/notes/{{note_id}}

### Update Note by id
PUT http://localhost:8080/notes/{{note_id}}
Content-Type: application/json

{
  "title": "Updated Title 3",
  "content": "Updated Content 1",
  "author": "New Author"
}
